### ISSUE TITLE
net.zetetic.database.sqlcipher.SQLiteConstraintException thrown if @Upsert is used

### ISSUE THREAD

**Issue by AleksandarIlic** [sqlcipher/sqlcipher-android#23]
I have implemented the sqlcipher-android in this commit:
https://github.com/PrimalHQ/primal-android-app/commit/4bc4482565e6c0941ca859faae21822e8a347d3d

If I run clean install build I'm getting:
```
net.zetetic.database.sqlcipher.SQLiteConstraintException: UNIQUE constraint failed: ProfileData.ownerId (code 1555)
	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:815)
	at net.zetetic.database.sqlcipher.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:823)
	at net.zetetic.database.sqlcipher.SQLiteStatement.executeInsert(SQLiteStatement.java:113)
	at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.kt:51)
	at androidx.room.EntityUpsertionAdapter.upsert(EntityUpsertionAdapter.kt:91)
	at net.primal.android.profile.db.ProfileDataDao_Impl.upsertAll(ProfileDataDao_Impl.java:165)
	.....
```

It turns out that `@Upsert` is the cause of the crash. If we replace it with `@Insert(onConflict = OnConflictStrategy.REPLACE)` everything works fine. https://github.com/PrimalHQ/primal-android-app/commit/a46232a1f390f9d0418b4f6189d6ed1d1646d5dc

**Comment by developernotes** [comment]
Hi @AleksandarIlic

Does it work using `@Upsert` if you use `@PrimaryKey(autoGenerate = true)` within your entities?

**Comment by AleksandarIlic** [comment]
Hi @developernotes,

It's not applicable. Our primary keys are Strings and sometimes two or more String fields. `@PrimarKey` can be applied only to ints and longs.
