### ISSUE TITLE
android.database.sqlite.SQLiteException - file is not a database (code 26)

### ISSUE THREAD

**Issue by UKMIITB** [sqlcipher/sqlcipher-android#32]
Fatal Exception: android.database.sqlite.SQLiteException: file is not a database (code 26): , while compiling: SELECT COUNT(*) FROM sqlite_schema;
#################################################################
Error Code : 26 (SQLITE_NOTADB)
Caused By : File opened that is not a database file or encrypted.
	(file is not a database (code 26): , while compiling: SELECT COUNT(*) FROM sqlite_schema;)
#################################################################
       at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
       at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:973)
       at net.zetetic.database.sqlcipher.SQLiteConnection.executeForLong(SQLiteConnection.java:628)
       at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:240)
       at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:202)
       at net.zetetic.database.sqlcipher.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:474)
       at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:189)
       at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
       at net.zetetic.database.sqlcipher.SQLiteDatabase.openInner(SQLiteDatabase.java:1028)
       at net.zetetic.database.sqlcipher.SQLiteDatabase.open(SQLiteDatabase.java:1013)
       at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:840)
       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:359)
       at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:278)
       at net.zetetic.database.sqlcipher.SupportHelper.getWritableDatabase(SupportHelper.java:60)
       at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:638)
       at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:457)
       at androidx.room.RoomDatabase.query(RoomDatabase.kt:486)
       at androidx.room.util.DBUtil.query(DBUtil.kt:75)

I am getting this crash in production. 
Its not happening for all users & not reproducible. But in production this is happening.

This is the code for initialisation.

`@Singleton
    @Provides
    fun providesAppEncryptedDatabase(
        @ApplicationContext context: Context
    ): AppEncryptedDatabase {
        var passphrase =
            PreferenceManager.getSecureStringApp(KEY_DB_ENCRYPTION)
                ?.toByteArray(Charsets.ISO_8859_1)
        if (passphrase == null) {
            passphrase =CommonUtils.generatePassphrase()
            PreferenceManager.saveStringSecurelyApp(
                key = KEY_DB_ENCRYPTION,
                value = passphrase.toString(Charsets.ISO_8859_1)
            )
        }
        try {
            SplitInstallHelper.loadLibrary(context, "sqlcipher")
        } catch (e: Exception) {
            e.log()
            try {
                System.loadLibrary("sqlcipher")
            } catch (e: Exception) {
                e.log()
            }
        }

        val sqlCipherOpenerFactory = SupportOpenHelperFactory(passphrase, null, true)
        return Room.databaseBuilder(
                context,
                AppEncryptedDatabase::class.java,
                ENCRYPTED_DATABASE_NAME
            )
            .openHelperFactory(sqlCipherOpenerFactory)
            .build()
    }`

So here once passphrase is generated same passphrase is getting used. And we donot clear that passphrase from shared preference, so the case of trying to open from another passphrase would not happen.

**Comment by sjlombardo** [comment]
Hello @UKMIITB In this case something is causing the key mismatch. There is not enough information to determine what, but that error is thrown when the incorrect key is used. You should check all the various edge cases, e.g. the implementations for your secured preferences, and any ways that a database could be used without a corresponding preference (e.g. restore from backup, transfer onto a different device, generation of passphrase, etc).

**Comment by GrenderG** [comment]
I was able to reproduce this issue with a 100% "success" rate, @sjlombardo. I'm testing this on a Pixel 7A with Android 34 and version `4.5.7` of the library. I'm using Room with a **hardcoded** password, so the issue isn't related to password mismatches.

Essentially, in my case, the application always crashes if I try to insert an item and I have never performed any SELECT statement before.

**Comment by developernotes** [comment]
Hi @GrenderG,

Can you post a public repo with a small test reproduction of the behavior you are seeing? We would be happy to investigate this further with a test case. Thanks!

**Comment by GrenderG** [comment]
Hello, I can try to do that this week. However, it should be very simple to test; basically you just need to open the app for the first time, then try to insert data without having performed any SELECT query before.

For the record, this is how I get the instance:

```java
public static synchronized DummyDatabase getInstance(Context context) {
    System.loadLibrary("sqlcipher");
    return Room.databaseBuilder(context.getApplicationContext(),
                    DummyDatabase.class, Constants.DATABASE_NAME)
            .fallbackToDestructiveMigration()
            .setAutoCloseTimeout(60, TimeUnit.SECONDS)
            .openHelperFactory(new SupportOpenHelperFactory(
                    Constants.DB_DEFAULT_PASSWORD.getBytes(StandardCharsets.UTF_8)))
            .build();
}
```
To note:

- All calls are being done inside `AsyncTasks`, in case it matters.
- INSERT, SELECT actions are done through [Room DAOs.](https://developer.android.com/training/data-storage/room/accessing-data#java)

**Comment by sjlombardo** [comment]
@GrenderG - in the scenario you are describing, does does the database already exist, or is the application creating a new database?

**Comment by GrenderG** [comment]
> @GrenderG - in the scenario you are describing, does does the database already exist, or is the application creating a new database?

The application is creating a new database.

**Comment by developernotes** [comment]
Hi @GrenderG,

Can you take a look at [this](https://github.com/developernotes/sqlcipher-android-room-demo) small demo application and compare with what you are seeing locally?

**Comment by GrenderG** [comment]
Hello, I tried it and the crash wasn't happening (my app is made with Java, not Kotlin, probably not relevant though). However, I found a way to avoid the crash in my scenario: if I use `ExecutorService` instead of a normal `AsyncTask`, it will work fine.

**Comment by developernotes** [comment]
Hi @GrenderG,

Thanks for the update, glad to hear you were able to resolve the issue.

**Comment by mandrachek** [comment]
I am experiencing the same issue.  We're storing the key in encrypted shared preferences for several different databases, and setting the key if it doesn't exist.  I wonder if we're hitting an odd race condition in shared prefs, or if it's something internal to sqlcipher.

**Comment by EpariNigam** [comment]
Hey @mandrachek a thread is going on for your use case

https://github.com/sqlcipher/sqlcipher-android/issues/34

**Comment by evgeny** [comment]
I have the same issue as @UKMIITB described. The crash happens for many users but I can't reproduce it. I have almost the same implementation. I assume that the problem started to happen when I migrated from the `net.zetetic:android-database-sqlcipher:4.5.4` to `net.zetetic:sqlcipher-android:4.6.0`

My implementation
```kotlin
object BookingsDatabaseFactory {

    private const val databaseName = "db"

    @JvmStatic
    val bookingsDatabase by lazy {
        val context = MyApp.appContext

        val factory = if (!BuildConfigProviderImpl().isDebug) {
            val dbPassword = EwKeyStore.getPassphrase()
            System.loadLibrary("sqlcipher")
            SupportOpenHelperFactory(dbPassword)
        } else {
            null
        }

        val dbBuilder = Room.databaseBuilder(
            context,
            BookingsDatabase::class.java,
            databaseName
        )
        if (RuntimeTestProviderImpl().isRunningTest) {
            dbBuilder.allowMainThreadQueries()
            dbBuilder.setTransactionExecutor(Executors.newSingleThreadExecutor())
        }
        dbBuilder.openHelperFactory(factory)
        dbBuilder.addMigrations(MIGRATION_11_12)
        dbBuilder.fallbackToDestructiveMigration()
        dbBuilder.build()
    }
}
```

```kotlin
    fun getPassphrase(): ByteArray {
        val applicationContext = MyApp.appContext
        val masterKey = MasterKey.Builder(applicationContext)
            .setKeyScheme(MasterKey.KeyScheme.AES256_GCM)
            .build()

        val file = File(applicationContext.filesDir, "passphrase.bin")
        val encryptedFile = EncryptedFile.Builder(
            applicationContext,
            file,
            masterKey,
            EncryptedFile.FileEncryptionScheme.AES256_GCM_HKDF_4KB
        ).build()

        return if (file.exists()) {
            encryptedFile.openFileInput().use { it.readBytes() }
        } else {
            generatePassphrase().also { passphrase ->
                encryptedFile.openFileOutput().use { it.write(passphrase) }
            }
        }
    }
    ```
    
    Any idea why it happens and how to fix this?

**Comment by xutao1266** [comment]
I previously encountered the same issue. The problem occurred because the database was encrypted using version 3.x, and upgrading to version 4.x triggered the above problem. I resolved it with the following code:
static class MigrateHook implements SQLiteDatabaseHook {

    @Override
    public void preKey(SQLiteConnection connection) {
    }

    @Override
    public void postKey(SQLiteConnection connection) {
        CancellationSignal signal = new CancellationSignal();
        try {
            connection.execute(
                    "PRAGMA cipher_migrate;",
                    new Object[0],
                    signal
            );
        } catch (Exception e) {
            Log.e(TAG, "Cipher migration failed: " + e.getMessage());
        } finally {
            signal.cancel();
        }
    }
}

**Comment by emyca** [comment]
Hi, everybody. In spite of my remark may be too late, I'd like to share my case of

```text
Fatal Exception: android.database.sqlite.SQLiteException: file is not a database (code 26): , while compiling: SELECT COUNT(*) FROM sqlite_schema;
...
Caused By : File opened that is not a database file or encrypted.
	(file is not a database (code 26): , while compiling: SELECT COUNT(*) FROM sqlite_schema;)
```

My app crashed during testing on physical device.

My solution was to add proper extension to database name. It looks like this:

```kotlin
    ...
    @Provides
    @Singleton
    fun provideLocalDatabase(
        @ApplicationContext context: Context
    ): AppDatabase {
        System.loadLibrary("sqlcipher")
        val dbPass = PassUtil().getPass() // gets DB password from storage
        val factory = SupportOpenHelperFactory(
            dbPass.toByteArray(StandardCharsets.UTF_8)
        )
        return Room.databaseBuilder(
            context,
            AppDatabase::class.java,
            "app_dbase.db" // <- The app crashes without 'db' file extension
        ).createFromAsset("database/some_dbase.db")
            .openHelperFactory(factory)
            .build()
    }
   ...
```

May be someone it will help. Thank you.
