### ISSUE TITLE
According to the configuration error, the database cannot be opened.

### ISSUE THREAD

**Issue by CodeLoverlyn** [sqlcipher/sqlcipher-android#39]
I am using version 4.6.0, the following is my error log：

Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteConnection.nativeOpen(Native Method)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:226)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:202)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:475)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:189)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteDatabase.openInner(SQLiteDatabase.java:1028)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteDatabase.open(SQLiteDatabase.java:1013)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:840)
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:919)
                                                                                                    	at com.example.minespringbootdemo.application.MineApplication.initSqlite(MineApplication.kt:86)
                                                                                                    	at com.example.minespringbootdemo.application.MineApplication.onCreate(MineApplication.kt:29)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7094)
                                                                                                    	at android.app.ActivityThread.access$1700(ActivityThread.java:275) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2168) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210) 
                                                                                                    	at android.os.Looper.loop(Looper.java:299) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8280) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073) 

Below is my code：
![image](https://github.com/sqlcipher/sqlcipher-android/assets/170616972/c815bd27-99c9-4126-b583-d103468e887f)

The error occurs in this line： mSQLiteDatabase =SQLiteDatabase.openOrCreateDatabase(databaseFile, key, null, null, null)
What could be the reason?

**Comment by developernotes** [comment]
Hi @CodeLoverlyn,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
