### ISSUE TITLE
net.zetetic.database.sqlcipher.SQLiteException: unknown error (code 0): Queries can be performed using SQLiteDatabase query or rawQuery methods only.

### ISSUE THREAD

**Issue by Chozzle** [sqlcipher/sqlcipher-android#6]
I am trying to handle migration for SQLCipher 3 to 4 using a `SQLiteDatabaseHook`. This code fails with the error:
`net.zetetic.database.sqlcipher.SQLiteException: unknown error (code 0): Queries can be performed using SQLiteDatabase query or rawQuery methods only.`

```java
@Override
public void postKey(SQLiteConnection connection) {
    connection.execute("PRAGMA cipher_migrate", null, null);
}
```

However there is a workaround to use one of the other methods which returns a value. It seems like the default execute method isn't compatible with the latest Android restrictions. This code works:

```java
@Override
public void postKey(SQLiteConnection connection) {
    connection.executeForString("PRAGMA cipher_migrate", null, null);
}
```

**Comment by developernotes** [comment]
Hi @Chozzle 

The API is slightly different between the legacy and new version of SQLCipher for Android. The `execute(...)` [^1] method does not expect a result to be returned, whereas `executeForString(...)` [^2] expects a single result. The `PRAGMA cipher_migrate` command returns a result code that reflects the success or failure of the migration.

[^1]: https://github.com/sqlcipher/sqlcipher-android/blob/master/sqlcipher/src/main/java/net/zetetic/database/sqlcipher/SQLiteConnection.java#L562-L601
[^2]: https://github.com/sqlcipher/sqlcipher-android/blob/master/sqlcipher/src/main/java/net/zetetic/database/sqlcipher/SQLiteConnection.java#L646-L687

**Comment by xuhongchang** [comment]
i have the same problem

android.database.sqlite.SQLiteException: SQL logic error (code 1): , while compiling: SELECT COUNT(*) FROM sqlite_schema;
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:973)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForLong(SQLiteConnection.java:628)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:240)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:202)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:475)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:189)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.openInner(SQLiteDatabase.java:1028)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.open(SQLiteDatabase.java:1013)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:840)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:359)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:278)

here is my code :
 public void postKey(SQLiteConnection connection) {
       
              String s=  connection.executeForString("PRAGMA cipher_migrate", null, null);
    
            }

**Comment by developernotes** [comment]
Hi @xuhongchang,

Try calling `executeForLong` instead as `PRAGMA cipher_migrate` will return a numeric result code. We have an example within the test suite [here](https://github.com/sqlcipher/sqlcipher-android/blob/master/sqlcipher/src/androidTest/java/net/zetetic/database/sqlcipher_cts/MigrateDatabaseFrom1xFormatToCurrentFormatTest.java#L28).

**Comment by xuhongchang** [comment]
What is the difference between executeForString and executeForLong besides the different return value types?

**Comment by xuhongchang** [comment]
There's still a problem.   from android-database-sqlcipher 3.5.9 to sqlcipher-android4.5.6

(1) SQL logic error in "SELECT COUNT(*) FROM sqlite_schema;"
2024-03-25 10:38:21.994 10557-10557 SQLiteDatabase          com.quvii.qvhome                    E  Failed to open database '/data/user/0/com.quvii.qvhome/databases/QvFun.db'.
                                                                                                   android.database.sqlite.SQLiteException: SQL logic error (code 1): , while compiling: SELECT COUNT(*) FROM sqlite_schema;
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:973)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForLong(SQLiteConnection.java:628)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:240)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:202)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:475)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:189)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.openInner(SQLiteDatabase.java:1028)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.open(SQLiteDatabase.java:1013)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:840)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:359)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:278)

**Comment by xuhongchang** [comment]
I made a mistake up there.The query does not have a lesser * number,and execute in post key method 
`long result = connection.executeForLong("PRAGMA cipher_migrate;", null, null);`
the result is 1.

environments：from android-database-sqlcipher 3.5.9 to sqlcipher-android4.5.6

error log：
```

SQLiteConnection        com.test.test                    I  Database keying operation returned:0
2024-03-26 09:50:28.292 30747-30747 X-LOG                   com.test.test                    I  SQLCipherHelperImpl$1.postKey(L:30): SQLCipherHelperImpl  postKey
2024-03-26 09:50:28.819 30747-30747 SQLiteLog               com.test.test                    E  (26) statement aborts at 2: [PRAGMA user_version;] file is not a database
2024-03-26 09:50:28.932 30747-30747 SQLiteLog               com.test.test                    E  (26) statement aborts at 2: [PRAGMA user_version;] file is not a database
2024-03-26 09:50:28.941 30747-30747 SQLiteLog               com.test.test                    E  (26) statement aborts at 2: [PRAGMA user_version;] file is not a database
2024-03-26 09:50:28.957 30747-30747 SQLiteLog               com.test.test                    E  (26) statement aborts at 2: [PRAGMA user_version;] file is not a database
2024-03-26 09:50:28.959 30747-30747 			            com.test.test                    W  JNI critical lock held for 654.839ms on Thread[1,tid=30747,Runnable,Thread*=0x7df1d33800,peer=0x72769888,"main"]
2024-03-26 09:50:28.962 30747-30747 X-LOG                   com.test.test                    I  SQLCipherHelperImpl$1.postKey(L:35): post key:1
2024-03-26 09:50:28.963 30747-30747 SQLiteLog               com.test.test                    E  (1) SQL logic error in "SELECT COUNT(*) FROM sqlite_schema;"
2024-03-26 09:50:28.968 30747-30747 SQLiteDatabase          com.test.test                    E  Failed to open database '/data/user/0/com.test.test/databases/Test.db'.
                                                                                                   android.database.sqlite.SQLiteException: SQL logic error (code 1): , while compiling: SELECT COUNT(*) FROM sqlite_schema;
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:973)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.executeForLong(SQLiteConnection.java:628)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:240)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnection.open(SQLiteConnection.java:202)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:475)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:189)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteConnectionPool.open(SQLiteConnectionPool.java:181)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.openInner(SQLiteDatabase.java:1028)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.open(SQLiteDatabase.java:1013)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteDatabase.openDatabase(SQLiteDatabase.java:840)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:359)
                                                                                                   	at net.zetetic.database.sqlcipher.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:278)
```


how to use shell command to migrate?

**Comment by developernotes** [comment]
Hi @xuhongchang,

When you have the SQLCipher command line shell, you can provide the key material and perform the `PRAGMA cipher_migrate;` command [^1].

[^1]: https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate

**Comment by xuhongchang** [comment]
> 你好[@xuhongchang](https://github.com/xuhongchang)，
> 
> 当您拥有 SQLCipher 命令行 shell 时，您可以提供密钥材料并执行`PRAGMA cipher_migrate;`命令[1](#user-content-fn-1-2e9d17a223dc6f8b3d2d4f0e6ed271fc)。
> 
> ## 脚注
> 1. [https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate ](https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate) [↩](#user-content-fnref-1-2e9d17a223dc6f8b3d2d4f0e6ed271fc)

![Image](https://github.com/user-attachments/assets/f9391cbb-fd91-4c5b-b534-24328becb017) 
here is result

I canuse SQLCipher3 open my database,  but i can't use SQLCipher4 open it

**Comment by xuhongchang** [comment]
> Hi [@xuhongchang](https://github.com/xuhongchang),
> 
> When you have the SQLCipher command line shell, you can provide the key material and perform the `PRAGMA cipher_migrate;` command [1](#user-content-fn-1-2e9d17a223dc6f8b3d2d4f0e6ed271fc).
> 
> ## Footnotes
> 1. https://www.zetetic.net/sqlcipher/sqlcipher-api/#cipher_migrate [↩](#user-content-fnref-1-2e9d17a223dc6f8b3d2d4f0e6ed271fc)


here is result

![Image](https://github.com/user-attachments/assets/2c4f0a86-0483-45c6-acf1-44de7bf710af)

I canuse SQLCipher3 open my database, but i can't use SQLCipher4 open it

i dont know how to use command line ,so i use gui download from [https://sqlitebrowser.org/dl/](url)

if you need i use command line ,please tell me where to download environment

**Comment by developernotes** [comment]
Hi @xuhongchang,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
