### ISSUE TITLE
Room integration issue

### ISSUE THREAD

**Issue by richardgarcar** [sqlcipher/sqlcipher-android#7]
Attempt to migrate application that uses Room library from previous version of SQLCipher for Android have failed with exception:

```
net.zetetic.database.sqlcipher.SQLiteException: no such table: room_table_modification_log (code 1): , while compiling: INSERT OR IGNORE INTO room_table_modification_log VALUES(2, 0)
at net.zetetic.database.sqlcipher.SQLiteConnection.nativePrepareStatement(Native Method)
at net.zetetic.database.sqlcipher.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:922)
at net.zetetic.database.sqlcipher.SQLiteConnection.prepare(SQLiteConnection.java:533)
at net.zetetic.database.sqlcipher.SQLiteSession.prepare(SQLiteSession.java:592)
at net.zetetic.database.sqlcipher.SQLiteProgram.(SQLiteProgram.java:64)
at net.zetetic.database.sqlcipher.SQLiteStatement.(SQLiteStatement.java:37)
at net.zetetic.database.sqlcipher.SQLiteDatabase.executeSql(SQLiteDatabase.java:1992)
at net.zetetic.database.sqlcipher.SQLiteDatabase.execSQL(SQLiteDatabase.java:1901)
at androidx.room.InvalidationTracker.startTrackingTable(InvalidationTracker.java:250)
at androidx.room.InvalidationTracker.syncTriggers(InvalidationTracker.java:559)
at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:567)
at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:555)
```

Table from exception is in-memory table used and managed by Room library. Table creation is called from `RoomOpenHelper.onOpen(SupportSQLiteDatabase db)` method. `RoomOpenHelper` is passed as the `callback` of `Configuration` passed to `SupportHelper`.

It looks like the issue is caused by difference in implementation of `SupportHelper` class in [previous](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/database/SupportHelper.java) version of SQLCipher for Android and the [recent](https://github.com/sqlcipher/sqlcipher-android/blob/master/sqlcipher/src/main/java/net/zetetic/database/sqlcipher/SupportHelper.java) one. Recent version is missing onOpen(SQLiteDatabase db) implementation that would call `callback.onOpen(db)`.

Is there any specific reason to to not override `onOpen` method in the recent version?

**Comment by developernotes** [comment]
Hi @richardgarcar,

Thank you for pointing out the discrepancy between the two support helper implementations. I have just pushed up a fix to include support for `onDowngrade`, `onOpen`, and `onConfigure` within the `SupportHelper`. This will be included in the next public release. Thanks!

**Comment by richardgarcar** [comment]
Thank you! May I ask what is the planned date of the next public release?

**Comment by developernotes** [comment]
Hi @richardgarcar,

We don't have a date to share at the moment. We will publish an announcement here [^1] if you are interested in receiving updates.

[^1]: https://discuss.zetetic.net/c/sqlcipher

**Comment by richardgarcar** [comment]
Retested with version 4.5.3 - issue has been solved.

**Comment by developernotes** [comment]
Hi @richardgarcar,

Thank you for your follow-up confirmation!
